### ISSUE TITLE
"Multivariable calculus": Are VVF really functions in an affine space ?

### ISSUE THREAD

**Issue by pcopissa** [wmboyles/Math-Summaries#18]
I am not sure that your entire chapter 2 should be called "Vector-Valued Functions". I believe what you are really describing are affine spaces and functions values therein. Indeed, this transpires in your definitions:

r(t) = P0 + t.(P1 - P0)

where you put arrows on P0 and P1 to denote them as vector, and yet you call P0 and P1 "points" in the text. You are really defining the usual curves in an affine space, where "points" live (not vectors). Vectors are the difference between points (so P1-P0 is a vector, even though P1 and P0 are not). Likewise, the sum of a vector and a point is a point. r(t) in that context is really a point, as it is the sum of point P0 and vector t.(P1 - P0).

I think you should rewrite chapter 2 by considering points in an affine space and not merely vectors.

**Comment by wmboyles** [comment]
If I recall from my calc 3 class on which the multicalc summary is based and from which I borrowed a lot of the content (including the name of this particular chapter), we didn't make a huge distinction between vectors and points. Visually, we were told to imagine vectors as "arrows" with their tails (usually) rooted at the origin, while the points were the zero-dimensional "dots" at the tip of a vector. In essence if you wanted to "convert" a point to a vector, you'd just look at the difference between the point and the origin.

Given that the name came from somewhere, and I don't think the distinction makes any of the concepts easier, else I'm a bit hesitant to make the change for now.
