### ISSUE TITLE
"Multivariable Calculus" section 6.2, 6.3.

### ISSUE THREAD

**Issue by Suzukazole** [wmboyles/Math-Summaries#22]
There seems to be an inconsistency in the use of \circ and \dot for representing dot products. Usually, \dot is used and it is better for this case, as \circ is used to represent tensor products.

**Comment by wmboyles** [comment]
Looking through 6.2 and 6.2, it looks like I tend to use `\circ` when taking the pullback, which is similar to function composition, hence the use of `\circ`.

I describe pullback and introduce the notation in 6.2 on the bottom of page 35:
![image](https://user-images.githubusercontent.com/40878829/103141707-239ea300-46c6-11eb-9994-55bc55dc3dea.png)

Meanwhile, I use `\dot` to represent dot products.

Here's an example in 6.2, page 37 that I think shows how each of the notations are used:
![image](https://user-images.githubusercontent.com/40878829/103141750-e2f35980-46c6-11eb-9786-eb004412640c.png)

As for `\circ` being use for tensor products, I've generally seen `\otimes` for them, while `\circ` is for function composition.

**Comment by Suzukazole** [comment]
Oh,that makes sense. I must have overlooked it while reading, my bad.
