### ISSUE TITLE
Crediting contributors

### ISSUE THREAD

**Issue by wmboyles** [wmboyles/Math-Summaries#3]
I'd like to give proper credit to those who make contributions. I don't think it's feasible to put everyone as an author on the title page. If you have any ideas on how to credit contributors in the text, please put it here.

**Comment by Suzukazole** [comment]
You could create an Acknowledgements section.

**Comment by wmboyles** [comment]
> You could create an Acknowledgements section.

That seems like a reasonable idea. I'd like for each work to have the same acknowledgement section. I'm not sure if LaTeX will like me trying to add a .tex file that's "higher" in the file tree than the main.tex file, but I'll look into in and see if it can work.
