### ISSUE TITLE
Adding releases

### ISSUE THREAD

**Issue by rawsh** [wmboyles/Math-Summaries#6]
If you released a zip with all the compiled latex docs that would probably be a lot easier for someone just looking for the summaries that doesn't need to edit them

**Comment by wmboyles** [comment]
At one point I did have the PDF in the repo, but another user suggested removing them and other binary files and only tracking source files. Right now, I will periodically put the PDF files [here](https://wmboyles.com/Projects/Projects.html#project-4) (under links "81-page guide" and "92-page summary").

One thing I may also consider is using the releases feature on GitHub to mark certain commits that purposely include the PDFs. Do you think this would be a better approach?

**Comment by wmboyles** [comment]
I have decided to to ahead and include the PDFs as part of the repo. Although it might be an extra file that is changed with pretty much every commit, it's pretty small, and I think it's more important that people are able to get the PDF for themselves without compiling if they want. This was changed in #10 .

**Comment by rawsh** [comment]
Nice thanks, yep I think that adding it in the Release would work too, thanks for adding this
Also I you could look at enabling github pages to host the pdf
