### ISSUE TITLE
Avoid using "i" in discrete sums

### ISSUE THREAD

**Issue by pcopissa** [wmboyles/Math-Summaries#9]
I strongly suggest not to use "i" as an index in discrete sums. "i" should be reserved for √-1. For your discrete sum index, use "k" instead.

I do know that context is sufficient to tell the difference, but remember that your target audience is learning about all this stuff. Do them a favor and avoid confusing notations.

**Comment by wmboyles** [comment]
Thanks for the suggestion. Going through the document, I realized there were several mistakes involving using the wrong variable with sums that are now also fixed.

**Comment by pcopissa** [comment]
Searching the PDF for "i=" yields a single occurrence, in 8.4.5, closing example p130.
